quarkus.datasource.user-store.db-kind=mysql
quarkus.datasource.user-store.username=${MONOLITH_DB_USERNAME}
quarkus.datasource.user-store.password=${MONOLITH_DB_PASSWORD}
quarkus.datasource.user-store.jdbc.url=${MONOLITH_DB_URL}
quarkus.datasource.user-store.jdbc.max-size=50
quarkus.datasource.user-store.jdbc.transactions=xa

quarkus.datasource.user-store-auth.db-kind=mysql
quarkus.datasource.user-store-auth.username=${AUTH_DB_USERNAME}
quarkus.datasource.user-store-auth.password=${AUTH_DB_PASSWORD}
quarkus.datasource.user-store-auth.jdbc.url=${AUTH_DB_URL}
quarkus.datasource.user-store-auth.jdbc.max-size=50
quarkus.datasource.user-store-auth.jdbc.transactions=xa