services:
  monolith-users-database:
    image: ${ECR}mysql:8.4
    container_name: monolith-users-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monolith
    volumes:
      - monolith-users-db:/var/lib/mysql-db/data
      - ./keycloak/scripts/users-database/create-test-monolith-db-users.sql:/docker-entrypoint-initdb.d/setup.sql

  auth-users-database:
    image: ${ECR}mysql:8.4
    container_name: auth-users-database
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
      MYSQL_TCP_PORT: 3307
    volumes:
      - auth-users-db:/var/lib/mysql-db/data
      - ./keycloak/scripts/users-database/create-test-auth-db-users.sql:/docker-entrypoint-initdb.d/setup.sql

  keycloak:
    image: ${ECR}quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak
    security_opt:
      - seccomp:unconfined
    command:
      - "start-dev"
      - "--verbose"
      - "--http-port=9090"
      - "--log-level=INFO,org.keycloak.events:DEBUG"
      - "--import-realm"
    ports:
      - "9090:9090"
      - "9091:9090"
      - "9000:9000"
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=http://keycloak:9090
      - KC_HOSTNAME_ADMIN=http://localhost:9091
      - KC_METRICS_ENABLED=true
      - KC_FEATURES=persistent-user-sessions
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - MONOLITH_DB_USERNAME=root
      - MONOLITH_DB_PASSWORD=root
      - MONOLITH_DB_URL=jdbc:mysql://monolith-users-database:3306/monolith?isReadOnly=true
      - AUTH_DB_USERNAME=root
      - AUTH_DB_PASSWORD=root
      - AUTH_DB_URL=jdbc:mysql://auth-users-database:3307/auth?isReadOnly=true
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_VIRTUAL_HOST=/
      - PORTAL_HERO_SECRET=dSGJlZFLlIZN2ZCIXeW0lAWuq5bnzxHI
      - GEEK_MARKET_SECRET=KFVIMtIomC2vgIyUGb4ghhBgpHSRFcbD
      - INVENTARIO_PRO_SECRET=Q2CTUVOevUpl5t5t6NghzZftkGIgUOZE
      - IWAKY_SECRET=7RjkQu89SOXC4xkhZNzPQVBkyk1zDWfP
      - MOTORFLASH_SECRET=c484fd26e33760742d94ce2f3ab028b1
      - YUPOP_SECRET=3TrCXF5RzRAaesTimwQ9RLN8kOVTechR
      - WEB_SECRET=y4VY4HJ476pr7hykG5Hoi4UbAPRMnh48
    depends_on:
      - monolith-users-database
      - auth-users-database
      - keycloak-db
      - selenium
    restart: unless-stopped
    volumes:
      - ./keycloak/config/realms.json:/opt/keycloak/data/import/realm.json
      - ./keycloak/config/themes:/opt/keycloak/themes/
      - ./keycloak/extensions/event-listener/target/event-listener-api-connect-jar-with-dependencies.jar:/opt/keycloak/providers/event-listener-api-connect.jar
      - ./keycloak/extensions/access-token-mapper/target/access-token-mapper.jar:/opt/keycloak/providers/access-token-mapper.jar
      - ./keycloak/extensions/monolith-users/target/monolith-users-jar-with-dependencies.jar:/opt/keycloak/providers/monolith-users.jar
      - ./keycloak/extensions/monolith-users/conf/quarkus.properties:/opt/keycloak/conf/quarkus.properties

  keycloak-db:
    image: ${ECR}postgres:15.3
    container_name: keycloak-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
    command:
      -c max_prepared_transactions=10
    volumes:
      - keycloak-db:/var/lib/keycloak-db/data
    restart: unless-stopped

  selenium:
    image: ${ECR}seleniarm/standalone-chromium
    container_name: selenium
    ports:
      - "4444:4444"
    shm_size: 2g

  rabbitmq:
    image: ${ECR}rabbitmq:3.8.4-management
    container_name: rabbitmq-iam
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  keycloak-db:
  monolith-users-db:
  auth-users-db:
