services:

  users-database:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monolith
    volumes:
      - user-db:/var/lib/mysql-db/data
      - ./scripts/users-database/test-users-setup.sql:/docker-entrypoint-initdb.d/setup.sql

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command:
      - "start-dev"
      - "--http-port=9090"
      - "--log-level=INFO,org.keycloak.events:DEBUG"
      - "--import-realm"
    ports:
      - "9090:9090"
      - "9091:9090"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_HOSTNAME_ADMIN_URL=http://localhost:9091
      - MONOLITH_DB_USERNAME=root
      - MONOLITH_DB_PASSWORD=root
      - MONOLITH_DB_URL=jdbc:mysql://users-database:3306/monolith?isReadOnly=true
    depends_on:
      - users-database
      - keycloak-db
    restart: unless-stopped
    volumes:
      - ./config/realm.json:/opt/keycloak/data/import/realm.json
      - ./extensions/access-token-mapper/target/access-token-mapper.jar:/opt/keycloak/providers/access-token-mapper.jar
      - ./extensions/monolith-users/target/monolith-users-jar-with-dependencies.jar:/opt/keycloak/providers/monolith-users.jar
      - ./extensions/monolith-users/conf/quarkus.properties:/opt/keycloak/conf/quarkus.properties

  keycloak-db:
    #TODO: ensure the version is the best to simulate our production environment (https://www.keycloak.org/server/db)
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
    command:
      -c max_prepared_transactions=10
    volumes:
      - keycloak-db:/var/lib/keycloak-db/data
    restart: unless-stopped

volumes:
  keycloak-db:
  user-db:
