standard-flow-simulation {
    open-workload = true
    concurrent-users = 20
    duration = 30s
    keycloak {
        url = "https://iam.beta.wallapop.com:443"
        # url = "https://iam.wallapop.com:443" # (prod)
        realm = "wallapop-connect"
        users = 3
        users-prefix = "load-test-"
        clients = [
            "CLIENT-0-SECRET",  # CHANGE ME
            "CLIENT-1-SECRET",  # CHANGE ME OR REMOVE ME
            "CLIENT-2-SECRET",  # CHANGE ME OR REMOVE ME
        ]
        clients-prefix = "load-app-"
    }
    user-agent = "curl/8.5.0"
}
