application {
  name = IAM

  domain-event-bus {
      user = "resolve:secretsmanager:/prod/iam/rabbitmq/application:user"
      password = "resolve:secretsmanager:/prod/iam/rabbitmq/application:password"
      virtual-host = "resolve:secretsmanager:/prod/iam/rabbitmq/application:virtual-host"
      host = "resolve:secretsmanager:/prod/iam/rabbitmq/application:host"
      port = "resolve:secretsmanager:/prod/iam/rabbitmq/application:port"
      queue-prefix = iam
      delayed-retry = 5s
      publisher-threads = 2
      consumer-threads = 15
    }
  }