[global_tags]
  task-id = "<TASK_ID>"

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  omit_hostname = false

[[inputs.prometheus]]
  urls = ["http://${KEYCLOAK_HOST}:9000/metrics"]
  timeout = "5s"

[[outputs.influxdb]]
  urls = ["http://influxdb.wallapop.${ENV}:8086"]
  timeout = "5s"
  database = "keycloak"
  username = "admin"
  password = "admin"
