Description: "Alarms topics for IAM"

Parameters:
  Project:
    Type: String
    Default: iam
    AllowedValues: [ iam ]
  Environment:
    Type: String
    Default: prod
    AllowedValues: [ prod ]
  PagerDutyIntegrationUri:
    Type: String
    Description: PagerDuty integration URI
    Default: ''

Conditions:
  AlarmsEnabled: !Equals [ !Ref Environment, 'prod']

Resources:
  SoftAlarmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Project}-soft-alarms-${Environment}"

  HardAlarmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref PagerDutyIntegrationUri
          Protocol: https
      TopicName: !Sub "${Project}-hard-alarms"

  NotificationSlackChannelConfiguration:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Condition: AlarmsEnabled
    Properties:
      ConfigurationName: !Sub ${Project}-alarms
      IamRoleArn:
        Fn::ImportValue: ChatBot-Role
      SlackChannelId: 'C076QA45QCT'
      SlackWorkspaceId:
        Fn::ImportValue: ChatBot-Workspace
      SnsTopicArns:
        - !Ref SoftAlarmsTopic
        - !Ref HardAlarmsTopic

Outputs:
  SoftAlarmTopicArn:
    Description: Arn for the soft alarm SNS topic
    Value: !Ref SoftAlarmsTopic
    Export:
      Name: !Sub "${Project}-soft-alarms-topic-arn-${Environment}"
  HardAlarmTopicArn:
    Description: Arn for the hard alarm SNS topic
    Value: !Ref HardAlarmsTopic
    Export:
      Name: !Sub "${Project}-hard-alarms-topic"
