Description: "Keycloak database"

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [ prod ]
  ServiceName:
    Type: String
    Default: iam-keycloak
    AllowedValues: [ iam-keycloak ]

Resources:
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${ServiceName}-database-${Environment}"
      GroupDescription: !Sub "Security group for ${ServiceName}"
      VpcId:
        Fn::ImportValue: !Sub "${Environment}-vpc"
      SecurityGroupIngress:
        - FromPort: 5432
          IpProtocol: tcp
          SourceSecurityGroupId:
            Fn::ImportValue: !Sub "VPN-${Environment}-sg"
          ToPort: 5432
          Description: Allows access from VPN

  DatabaseClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: !Sub "Custom parameter group for ${ServiceName} database"
      Family: aurora-postgresql15
      Parameters:
        max_prepared_transactions: "400"

  DatabaseCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      StorageEncrypted: true
      EngineMode: provisioned
      Port: 5432
      DBClusterIdentifier: !Sub "${ServiceName}"
      DatabaseName: keycloak
      PreferredBackupWindow: 04:11-04:41
      NetworkType: IPV4
      VpcSecurityGroupIds:
        - !Ref DatabaseSecurityGroup
      CopyTagsToSnapshot: true
      Engine: aurora-postgresql
      EngineVersion: 15.4
      StorageType: aurora
      KmsKeyId: arn:aws:kms:eu-west-1:745640521341:key/a0c441a6-4d1d-4cb0-801f-45458c479b81
      ServerlessV2ScalingConfiguration:
        MinCapacity: 1
        MaxCapacity: 2
      PreferredMaintenanceWindow: wed:00:43-wed:01:13
      DBSubnetGroupName: core-prod-privatedbsubnetgroup-tosshypm7sdt
      DeletionProtection: true
      ManageMasterUserPassword: true
      MasterUserSecret:
        KmsKeyId: arn:aws:kms:eu-west-1:745640521341:key/3b2eab83-99d8-4133-9a1f-8f86b1e2fc39
      MasterUsername: postgres
      DBClusterParameterGroupName: !Ref DatabaseClusterParameterGroup
      BackupRetentionPeriod: 7

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DatabaseCluster
      DBParameterGroupName: default.aurora-postgresql15
      Engine: aurora-postgresql
      MultiAZ: false
      PerformanceInsightsKMSKeyId: arn:aws:kms:eu-west-1:745640521341:key/a0c441a6-4d1d-4cb0-801f-45458c479b81
      LicenseModel: postgresql-license
      DBInstanceClass: db.serverless
      PerformanceInsightsRetentionPeriod: 7
      OptionGroupName: default:aurora-postgresql-15
      PreferredMaintenanceWindow: sat:22:05-sat:22:35
      EnablePerformanceInsights: true
      AutoMinorVersionUpgrade: true
      DBSubnetGroupName:
        Fn::ImportValue: !Sub "${Environment}-rds-private-subnetgroup"
      DBInstanceIdentifier: !Sub "${ServiceName}-instance-1"
      CACertificateIdentifier: rds-ca-rsa2048-g1
      PubliclyAccessible: false

Outputs:
  DatabaseSecurityGroup:
    Description: Keycloak database security group
    Value: !Ref DatabaseSecurityGroup
    Export:
      Name: !Sub "${ServiceName}-database-security-group-${Environment}"
