Description: "Keycloak database"

Parameters:
  Project:
    Type: String
    Default: iam
    AllowedValues: [iam]
  Environment:
    Type: String
    Default: beta
    AllowedValues: [beta, prod]
  ServiceName:
    Type: String
    Default: iam-keycloak
    AllowedValues: [ iam-keycloak ]
  KmsKeyId:
    Type: String
  MasterKmsKeyId:
    Type: String

Conditions:
  AlarmsEnabled: !Equals [ !Ref Environment, 'prod']

Resources:
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${ServiceName}-database-${Environment}"
      GroupDescription: !Sub "Security group for ${ServiceName}"
      VpcId:
        Fn::ImportValue: !Sub "${Environment}-vpc"
      SecurityGroupIngress:
        - FromPort: 5432
          IpProtocol: tcp
          SourceSecurityGroupId:
            Fn::ImportValue: !Sub "VPN-${Environment}-sg"
          ToPort: 5432
          Description: Allows access from VPN

  DatabaseClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: !Sub "Custom parameter group for ${ServiceName} database"
      Family: aurora-postgresql15
      Parameters:
        max_prepared_transactions: "400"

  DatabaseCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      StorageEncrypted: true
      EngineMode: provisioned
      Port: 5432
      DBClusterIdentifier: !Sub "${ServiceName}"
      DatabaseName: keycloak
      PreferredBackupWindow: 04:11-04:41
      NetworkType: IPV4
      VpcSecurityGroupIds:
        - !Ref DatabaseSecurityGroup
      CopyTagsToSnapshot: true
      Engine: aurora-postgresql
      EngineVersion: 15.4
      StorageType: aurora
      KmsKeyId: !Sub "${KmsKeyId}"
      ServerlessV2ScalingConfiguration:
        MinCapacity: 1
        MaxCapacity: 2
      PreferredMaintenanceWindow: wed:00:43-wed:01:13
      DBSubnetGroupName:
        Fn::ImportValue: !Sub "${Environment}-rds-private-subnetgroup"
      DeletionProtection: true
      ManageMasterUserPassword: true
      MasterUserSecret:
        KmsKeyId: !Sub "${MasterKmsKeyId}"
      MasterUsername: postgres
      DBClusterParameterGroupName: !Ref DatabaseClusterParameterGroup
      BackupRetentionPeriod: 7

  ClusterConsumedCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmName: !Sub "${ServiceName}-${Environment}_database-capacity-consumption-near-maximum"
      AlarmDescription: !Sub "${ServiceName} - we are running out of provisioned capacity (ACUs) for the database"
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue: !Sub "${Project}-soft-alarms-topic-arn-${Environment}"
      OKActions:
        - Fn::ImportValue: !Sub "${Project}-soft-alarms-topic-arn-${Environment}"
      Namespace: AWS/RDS
      MetricName: ACUUtilization
      Dimensions:
        - Name: DBClusterIdentifier
          Value: !Ref DatabaseCluster
      Statistic: Maximum
      EvaluationPeriods: 5
      Period: 60
      ComparisonOperator: GreaterThanThreshold
      Threshold: 85

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DatabaseCluster
      DBParameterGroupName: default.aurora-postgresql15
      Engine: aurora-postgresql
      MultiAZ: false
      PerformanceInsightsKMSKeyId: !Sub "${KmsKeyId}"
      LicenseModel: postgresql-license
      DBInstanceClass: db.serverless
      PerformanceInsightsRetentionPeriod: 7
      OptionGroupName: default:aurora-postgresql-15
      PreferredMaintenanceWindow: sat:22:05-sat:22:35
      EnablePerformanceInsights: true
      AutoMinorVersionUpgrade: true
      DBSubnetGroupName:
        Fn::ImportValue: !Sub "${Environment}-rds-private-subnetgroup"
      DBInstanceIdentifier: !Sub "${ServiceName}-instance-1"
      CACertificateIdentifier: rds-ca-rsa2048-g1
      PubliclyAccessible: false

Outputs:
  DatabaseSecurityGroup:
    Description: Keycloak database security group
    Value: !Ref DatabaseSecurityGroup
    Export:
      Name: !Sub "${ServiceName}-database-security-group-${Environment}"
