AWSTemplateFormatVersion: "2010-09-09"
Description: >
  IAM RabbitMQ Secrets

Parameters:
  Project:
    Type: String
    Default: iam
    AllowedValues: [iam]
  Environment:
    Type: String
    Default: beta
    AllowedValues: [beta, prod]

Resources:
  RabbitMqSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "/${Environment}/${Project}/rabbitmq/application"
      Description: "IAM RabbitMQ credentials"
      GenerateSecretString:
        SecretStringTemplate:
          !Sub '{"user": "iam", "virtual-host": "wallapop", "host": "rabbitmq.wallapop.${Environment}", "port": 5672}'
        GenerateStringKey: "password"
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Role
          Value: "secret"
        - Key: Type
          Value: rabbitmq
