quarkus.datasource.user-store.db-kind=mysql
quarkus.datasource.user-store.username=${MONOLITH_DB_USERNAME}
quarkus.datasource.user-store.password=${MONOLITH_DB_PASSWORD}
quarkus.datasource.user-store.jdbc.url=${MONOLITH_DB_URL}
quarkus.datasource.user-store.jdbc.max-size=50