quarkus.datasource.user-store.db-kind=mysql
quarkus.datasource.user-store.username=root
quarkus.datasource.user-store.password=root
quarkus.datasource.user-store.jdbc.url=jdbc:mysql://users-database:3306/monolith?isReadOnly=true