<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <groupId>org.keycloak</groupId>
        <artifactId>keycloak-parent</artifactId>
        <version>24.0.4</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>monolith-users</artifactId>
    <packaging>jar</packaging>
    <description>Monolith User Storage Provider with JPA</description>

    <properties>
        <keycloak>24.0.4</keycloak>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-core</artifactId>
            <version>${keycloak}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-server-spi</artifactId>
            <version>${keycloak}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-model-jpa</artifactId>
            <version>${keycloak}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>monolith-users</finalName>
    </build>
</project>
